-- Public transplant-games meet catalogue seeded from transplant_games_events.json.
create table if not exists public.meet_catalog (
  id uuid primary key default gen_random_uuid(),
  catalog_key text not null unique,
  category text not null check (category in ('World Transplant Games', 'National Transplant Games')),
  category_order smallint not null check (category_order between 1 and 2),
  series_id text not null,
  series_name text not null,
  name text not null,
  year smallint not null,
  edition_number smallint,
  host_city text,
  host_country text,
  meet_date date,
  end_date date,
  status text not null check (status in ('completed', 'in_progress', 'upcoming', 'cancelled', 'date_unconfirmed')),
  source_url text,
  source_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or meet_date is null or end_date >= meet_date)
);

create index if not exists meet_catalog_picker_idx
  on public.meet_catalog (category_order, year desc, name);
create index if not exists meet_catalog_date_idx on public.meet_catalog (meet_date desc nulls last);

alter table public.meet_catalog enable row level security;
drop policy if exists "Meet catalogue is public" on public.meet_catalog;
create policy "Meet catalogue is public" on public.meet_catalog
  for select to anon, authenticated using (true);
grant select on public.meet_catalog to anon, authenticated;

insert into public.meet_catalog (
  catalog_key, category, category_order, series_id, series_name, name, year, edition_number,
  host_city, host_country, meet_date, end_date, status, source_url, source_metadata
) values
  ('world-transplant-games-summer:1:1978', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1978', '1978', '1', 'Portsmouth', 'United Kingdom', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1978,"number":1,"host_city":"Portsmouth","host_country":"United Kingdom","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:2:1979', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1979', '1979', '2', 'Portsmouth', 'United Kingdom', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1979,"number":2,"host_city":"Portsmouth","host_country":"United Kingdom","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:3:1980', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1980', '1980', '3', 'New York', 'United States', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1980,"number":3,"host_city":"New York","host_country":"United States","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:4:1982', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1982', '1982', '4', 'Athens', 'Greece', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1982,"number":4,"host_city":"Athens","host_country":"Greece","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:5:1984', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1984', '1984', '5', 'Amsterdam', 'Netherlands', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1984,"number":5,"host_city":"Amsterdam","host_country":"Netherlands","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:6:1987', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1987', '1987', '6', 'Innsbruck', 'Austria', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1987,"number":6,"host_city":"Innsbruck","host_country":"Austria","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:7:1989', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1989', '1989', '7', 'Singapore', 'Singapore', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1989,"number":7,"host_city":"Singapore","host_country":"Singapore","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:8:1991', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1991', '1991', '8', 'Budapest', 'Hungary', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1991,"number":8,"host_city":"Budapest","host_country":"Hungary","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:9:1993', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1993', '1993', '9', 'Vancouver', 'Canada', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1993,"number":9,"host_city":"Vancouver","host_country":"Canada","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:10:1995', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1995', '1995', '10', 'Manchester', 'United Kingdom', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1995,"number":10,"host_city":"Manchester","host_country":"United Kingdom","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:11:1997', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1997', '1997', '11', 'Sydney', 'Australia', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1997,"number":11,"host_city":"Sydney","host_country":"Australia","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:12:1999', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 1999', '1999', '12', 'Budapest', 'Hungary', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":1999,"number":12,"host_city":"Budapest","host_country":"Hungary","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:13:2001', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2001', '2001', '13', 'Kobe', 'Japan', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2001,"number":13,"host_city":"Kobe","host_country":"Japan","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:14:2003', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2003', '2003', '14', 'Nancy', 'France', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2003,"number":14,"host_city":"Nancy","host_country":"France","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:15:2005', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2005', '2005', '15', 'London, Ontario', 'Canada', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2005,"number":15,"host_city":"London, Ontario","host_country":"Canada","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:16:2007', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2007', '2007', '16', 'Bangkok', 'Thailand', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2007,"number":16,"host_city":"Bangkok","host_country":"Thailand","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:17:2009', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2009', '2009', '17', 'Gold Coast', 'Australia', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2009,"number":17,"host_city":"Gold Coast","host_country":"Australia","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:18:2011', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2011', '2011', '18', 'Gothenburg', 'Sweden', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2011,"number":18,"host_city":"Gothenburg","host_country":"Sweden","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:19:2013', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2013', '2013', '19', 'Durban', 'South Africa', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2013,"number":19,"host_city":"Durban","host_country":"South Africa","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:20:2015', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2015', '2015', '20', 'Mar del Plata', 'Argentina', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2015,"number":20,"host_city":"Mar del Plata","host_country":"Argentina","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:21:2017', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2017', '2017', '21', 'Malaga', 'Spain', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2017,"number":21,"host_city":"Malaga","host_country":"Spain","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:22:2019', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2019', '2019', '22', 'Newcastle and Gateshead', 'United Kingdom', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2019,"number":22,"host_city":"Newcastle and Gateshead","host_country":"United Kingdom","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:23:2021', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2021', '2021', '23', null, null, null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2021,"number":23,"host_city":null,"host_country":null,"format":"Virtual 5K AnyWay / online community event","status":"completed","notes":"The planned Houston in-person Games were cancelled during the COVID-19 pandemic; WTGF lists a virtual edition.","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:24:2023', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2023', '2023', '24', 'Perth', 'Australia', null, null, 'completed', 'https://wtgf.org/previous-games/', '{"year":2023,"number":24,"host_city":"Perth","host_country":"Australia","status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:25:2025', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2025', '2025', '25', 'Dresden', 'Germany', '2025-08-17', '2025-08-24', 'completed', 'https://wtgf.org/previous-games/', '{"year":2025,"number":25,"host_city":"Dresden","host_country":"Germany","dates":{"start":"2025-08-17","end":"2025-08-24"},"status":"completed","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('world-transplant-games-summer:26:2027', 'World Transplant Games', '1', 'world-transplant-games-summer', 'Summer World Transplant Games', 'Summer World Transplant Games 2027', '2027', '26', 'Leuven', 'Belgium', '2027-08-01', '2027-08-08', 'upcoming', 'https://wtgf.org/previous-games/', '{"year":2027,"number":26,"host_city":"Leuven","host_country":"Belgium","dates":{"start":"2027-08-01","end":"2027-08-08"},"status":"upcoming","series_id":"world-transplant-games-summer","series_name":"Summer World Transplant Games","source_urls":["https://wtgf.org/previous-games/","https://wtgf.org/results/","https://wtgf.org/wtgf-inspection-team-confirms-strong-progress-towards-the-2027-world-transplant-games-in-leuven/"]}'::jsonb),
  ('transplant-games-of-america:edition:2026', 'National Transplant Games', '2', 'transplant-games-of-america', 'Transplant Games of America', 'Transplant Games of America 2026', '2026', null, 'Denver, Colorado', 'United States', '2026-06-18', '2026-06-23', 'completed', 'https://www.transplantgamesofamerica.org/2026-transplant-games', '{"year":2026,"host_city":"Denver, Colorado","host_country":"United States","dates":{"start":"2026-06-18","end":"2026-06-23"},"status":"completed","sports_count":20,"program_note":"Organizer reported more than 60 special events and programs.","series_id":"transplant-games-of-america","series_name":"Transplant Games of America","source_urls":["https://www.transplantgamesofamerica.org/2026-transplant-games","https://www.transplantgamesofamerica.org/2028-transplant-games"]}'::jsonb),
  ('transplant-games-of-america:edition:2028', 'National Transplant Games', '2', 'transplant-games-of-america', 'Transplant Games of America', 'Transplant Games of America 2028', '2028', null, 'Saint Paul, Minnesota', 'United States', '2028-08-04', '2028-08-09', 'upcoming', 'https://www.transplantgamesofamerica.org/2026-transplant-games', '{"year":2028,"host_city":"Saint Paul, Minnesota","host_country":"United States","dates":{"start":"2028-08-04","end":"2028-08-09"},"status":"upcoming","series_id":"transplant-games-of-america","series_name":"Transplant Games of America","source_urls":["https://www.transplantgamesofamerica.org/2026-transplant-games","https://www.transplantgamesofamerica.org/2028-transplant-games"]}'::jsonb),
  ('australian-transplant-games:17:2024', 'National Transplant Games', '2', 'australian-transplant-games', 'Australian Transplant Games', 'Australian Transplant Games 2024', '2024', '17', 'Canberra, Australian Capital Territory', 'Australia', '2024-10-01', '2024-10-06', 'completed', 'https://transplant.org.au/about-the-games/', '{"year":2024,"number":17,"host_city":"Canberra, Australian Capital Territory","host_country":"Australia","dates":{"start":"2024-10-01","end":"2024-10-06"},"status":"completed","series_id":"australian-transplant-games","series_name":"Australian Transplant Games","source_urls":["https://transplant.org.au/about-the-games/","https://transplant.org.au/australian-transplant-games-2026-launch/","https://transplant.org.au/wp-content/uploads/2025/10/TA_Members-Update-2025-FA-Online.pdf"]}'::jsonb),
  ('australian-transplant-games:18:2026', 'National Transplant Games', '2', 'australian-transplant-games', 'Australian Transplant Games', 'Australian Transplant Games 2026', '2026', '18', 'Launceston, Tasmania', 'Australia', '2026-09-26', '2026-10-03', 'in_progress', 'https://transplant.org.au/about-the-games/', '{"year":2026,"number":18,"host_city":"Launceston, Tasmania","host_country":"Australia","dates":{"start":"2026-09-26","end":"2026-10-03"},"status":"in_progress","series_id":"australian-transplant-games","series_name":"Australian Transplant Games","source_urls":["https://transplant.org.au/about-the-games/","https://transplant.org.au/australian-transplant-games-2026-launch/","https://transplant.org.au/wp-content/uploads/2025/10/TA_Members-Update-2025-FA-Online.pdf"]}'::jsonb),
  ('canadian-transplant-games:edition:2026', 'National Transplant Games', '2', 'canadian-transplant-games', 'Canadian Transplant Games', 'Canadian Transplant Games 2026', '2026', null, 'Sherbrooke, Quebec', 'Canada', '2026-07-05', '2026-07-11', 'completed', 'https://www.canadiantransplant.com/2026-cta-games', '{"year":2026,"host_city":"Sherbrooke, Quebec","host_country":"Canada","dates":{"start":"2026-07-05","end":"2026-07-11"},"status":"completed","sports_note":"Organizer lists multiple sport events, including swimming.","series_id":"canadian-transplant-games","series_name":"Canadian Transplant Games","source_urls":["https://www.canadiantransplant.com/2026-cta-games","https://www.canadiantransplant.com/2026faqs","https://www.canadiantransplant.com/sports"]}'::jsonb),
  ('british-transplant-games:edition:2026', 'National Transplant Games', '2', 'british-transplant-games', 'British Transplant Games', 'British Transplant Games 2026', '2026', null, 'Sheffield', 'United Kingdom', '2026-08-06', '2026-08-09', 'completed', 'https://www.transplantactive.co.uk/britishtransplantgames/sheffield2026', '{"year":2026,"host_city":"Sheffield","host_country":"United Kingdom","dates":{"start":"2026-08-06","end":"2026-08-09"},"status":"completed","sports_count":24,"series_id":"british-transplant-games","series_name":"British Transplant Games","source_urls":["https://www.transplantactive.co.uk/britishtransplantgames/sheffield2026","https://www.transplantactive.co.uk/post/university-of-birmingham-to-host-2027-westfield-health-british-transplant-games","https://www.saka.org.uk/transplant-games/"]}'::jsonb),
  ('british-transplant-games:edition:2027', 'National Transplant Games', '2', 'british-transplant-games', 'British Transplant Games', 'British Transplant Games 2027', '2027', null, 'Birmingham', 'United Kingdom', '2027-07-29', '2027-08-01', 'upcoming', 'https://www.transplantactive.co.uk/britishtransplantgames/sheffield2026', '{"year":2027,"host_city":"Birmingham","host_country":"United Kingdom","dates":{"start":"2027-07-29","end":"2027-08-01"},"status":"upcoming","series_id":"british-transplant-games","series_name":"British Transplant Games","source_urls":["https://www.transplantactive.co.uk/britishtransplantgames/sheffield2026","https://www.transplantactive.co.uk/post/university-of-birmingham-to-host-2027-westfield-health-british-transplant-games","https://www.saka.org.uk/transplant-games/"]}'::jsonb),
  ('south-african-national-transplant-games:14:2022', 'National Transplant Games', '2', 'south-african-national-transplant-games', 'South African National Transplant Games', 'South African National Transplant Games 2022', '2022', '14', null, 'South Africa', null, null, 'completed', 'https://transplantsports.org.za/about/', '{"year":2022,"number":14,"host_city":null,"host_country":"South Africa","status":"completed","notes":"Organizer report identifies this as the 14th National Transplant Games; host city and dates are not included in this record.","series_id":"south-african-national-transplant-games","series_name":"South African National Transplant Games","source_urls":["https://transplantsports.org.za/about/","https://transplantsports.org.za/events-2/","https://transplantsports.org.za/wp-content/uploads/2023/10/1-Final-Report-NTG-2022-July-1.pdf"]}'::jsonb),
  ('south-african-national-transplant-games:edition:2026', 'National Transplant Games', '2', 'south-african-national-transplant-games', 'South African National Transplant Games', 'South African National Transplant Games 2026', '2026', null, 'Pretoria', 'South Africa', '2026-09-24', '2026-09-27', 'completed', 'https://transplantsports.org.za/about/', '{"year":2026,"host_city":"Pretoria","host_country":"South Africa","dates":{"start":"2026-09-24","end":"2026-09-27"},"status":"completed","series_id":"south-african-national-transplant-games","series_name":"South African National Transplant Games","source_urls":["https://transplantsports.org.za/about/","https://transplantsports.org.za/events-2/","https://transplantsports.org.za/wp-content/uploads/2023/10/1-Final-Report-NTG-2022-July-1.pdf"]}'::jsonb),
on conflict (catalog_key) do update set
  category = excluded.category, category_order = excluded.category_order, series_id = excluded.series_id,
  series_name = excluded.series_name, name = excluded.name, year = excluded.year, edition_number = excluded.edition_number,
  host_city = excluded.host_city, host_country = excluded.host_country, meet_date = excluded.meet_date,
  end_date = excluded.end_date, status = excluded.status, source_url = excluded.source_url,
  source_metadata = excluded.source_metadata, updated_at = now();

alter table public.submitted_meets
  add column if not exists catalog_meet_id uuid references public.meet_catalog(id) on delete set null;

drop index if exists public.submitted_meets_identity_idx;
create unique index if not exists submitted_meets_catalog_identity_idx
  on public.submitted_meets (catalog_meet_id, course, coalesce(opening_ceremony_date, meet_date))
  where catalog_meet_id is not null;
create unique index if not exists submitted_meets_custom_identity_idx
  on public.submitted_meets (lower(name), meet_date, lower(location), course, is_world_transplant_games, coalesce(opening_ceremony_date, meet_date))
  where catalog_meet_id is null;

create index if not exists submitted_meets_catalog_meet_idx on public.submitted_meets (catalog_meet_id);
